name: Auto-Label and Assign Issue

on:
  issues:
    types:
      - opened

jobs:
  label_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label and assign to creator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_CREATOR: ${{ github.event.issue.user.login }}
        run: |
          # Add a label to the issue
          curl -X POST -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
          -d '{"labels":["bug"]}'

          # Assign the issue to the creator
          curl -X PATCH -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
          -d "{\"assignees\":[\"$ISSUE_CREATOR\"]}"

          # Add a comment to greet the creator
          curl -X POST -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
          -d "{\"body\":\"@$ISSUE_CREATOR, you have been assigned to this issue. Congratulations!\"}"
