name: Tests for the backend

on:
    pull_request:
        branches: [ main ]
       
jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
          run:
             working-directory: ./backend
        strategy:
            matrix:
                node_version: [18,20]
        steps:
            - uses: actions/checkout@v2
            - name: Use node.js
              uses: actions/setup-node@v3
              with:
                node-version: "${{ matrix.node_version }}"
            - run: |
                 echo "$(pwd) is in $(ls)"
            - run: npm ci
            - run: npm run
              env:
                CI: true
